// Generated by lua5.1.js-file-packer
(function(Lua5_1) {
Lua5_1.provide_file("/hello-world/", "alert.lua",
 "return\n"
+"{\n"
+"  alert = function() ALERT(\"Hello, world!\") end;\n"
+"}\n",
true, false);
// End of /hello-world/alert.lua
Lua5_1.provide_file("/", "main.lua",
 "local alert = require 'hello-world.alert'\n"
+"alert.alert()\n",
true, false);
// End of /main.lua
})(Lua5_1);
